// filepath: src/utils/env-file.js
import fs from 'node:fs';
import path from 'node:path';

/**
 * Parse a .env file into a plain key/value object (without `export` prefixes).
 * Handles quoted values, blank lines, and comments.
 */
export function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const raw = fs.readFileSync(filePath, 'utf8');
  const env = {};
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const cleaned = trimmed.replace(/^export\s+/, '');
    const eq = cleaned.indexOf('=');
    if (eq === -1) continue;
    const key = cleaned.slice(0, eq).trim();
    let value = cleaned.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

/**
 * Serialize an env object back into a deterministic .env string.
 * Keys are sorted alphabetically for stable output.
 */
export function serializeEnv(env) {
  const lines = [
    '# Generated by embeddings-service',
    '# Sensitive values: do not commit this file.',
    '',
  ];
  for (const key of Object.keys(env).sort()) {
    const raw = String(env[key] ?? '');
    const safe = /^[A-Za-z0-9_./:=+-]*$/.test(raw) ? raw : JSON.stringify(raw);
    lines.push(`${key}=${safe}`);
  }
  return lines.join('\n') + '\n';
}

/**
 * Write the given env object to `filePath`, preserving existing keys that are
 * not present in the new payload. Creates parent directories and forces
 * 0600 permissions so API keys are not world-readable.
 */
export function writeEnvFile(filePath, env) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const current = parseEnvFile(filePath);
  const merged = { ...current, ...env };
  fs.writeFileSync(filePath, serializeEnv(merged), { mode: 0o600 });
  try {
    fs.chmodSync(filePath, 0o600);
  } catch {
    // best-effort: some filesystems (e.g. Windows) ignore chmod
  }
  return merged;
}

/**
 * Ensure the given key exists in `filePath`. If missing, returns the literal
 * value the caller passed; if present, returns its current value.
 */
export function ensureEnvEntry(filePath, key, value) {
  const current = parseEnvFile(filePath);
  if (current[key] !== undefined) return { value: current[key], created: false };
  writeEnvFile(filePath, { [key]: value });
  return { value, created: true };
}

/**
 * Pick the next free ENV-XXXX slot for a given provider prefix.
 * Used so multiple NVIDIA keys (e.g. embeddings + LLM) do not collide.
 */
export function nextEnvName(filePath, prefix) {
  const current = parseEnvFile(filePath);
  const safePrefix = prefix.toUpperCase().replace(/[^A-Z0-9]/g, '_');
  let i = 1;
  while (current[`${safePrefix}_${i}`] !== undefined) i += 1;
  return `${safePrefix}_${i}`;
}
